name: CI
on:
  push:
    paths:
      - '**.py'
    branches:
      - '!main'
  pull_request:
    paths:
      - '**.py'
    branches:
      - '*'
  workflow_dispatch:  

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    env: 
      version: vCI
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x64, arm64]
        include:
          - os: ubuntu-latest
            architecture: x64
            extension: ''
          - os: ubuntu-latest
            architecture: arm64
            extension: ''
          - os: windows-latest
            architecture: x64
            extension: '.exe'
          - os: windows-latest
            architecture: arm64
            extension: '.exe'
          - os: macos-latest
            architecture: x64
            extension: ''
          - os: macos-latest
            architecture: arm64
            extension: ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --junit-xml=test-results.xml tests/test.py

      - name: Publish Tests
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Check Site Test results

      - name: Build CLI executable
        run: pyinstaller check_site.py --onefile -n site-checker${{ matrix.extension }}

      - name: Test CLI executable
        run: |
          ./dist/site-checker${{ matrix.extension }} --version
          ./dist/site-checker${{ matrix.extension }} example.com
        env: 
          version: ${{ env.version }}