name: CI
on:
  push:
    paths:
      - '**.py'
    branches:
      - '!main'
  pull_request:
    paths:
      - '**.py'
    branches:
      - '*'
  workflow_dispatch:  

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --junit-xml=test-results.xml tests/test.py

      - name: Publish Tests
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Check Site Test results