name: Build and Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    env: 
      version: ${{ github.ref_name }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x64, arm64]
        include:
          - os: ubuntu-latest
            architecture: x64
            extension: ''
            artifact: linux-x64
          - os: ubuntu-latest
            architecture: arm64
            extension: ''
            artifact: linux-arm64
          - os: windows-latest
            architecture: x64
            extension: '.exe'
            artifact: windows-x64
          - os: windows-latest
            architecture: arm64
            extension: '.exe'
            artifact: windows-arm64
          - os: macos-latest
            architecture: x64
            extension: ''
            artifact: macos-x64
          - os: macos-latest
            architecture: arm64
            extension: ''
            artifact: macos-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --junit-xml=test-results.xml tests/test.py

      - name: Publish Tests
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Check Site Test results

      - name: Build CLI executable
        run: pyinstaller check_site.py --onefile -n site-checker${{ matrix.extension }}

      - name: Test CLI executable
        run: |
          ./dist/site-checker${{ matrix.extension }} --version
          ./dist/site-checker${{ matrix.extension }} example.com
        env: 
          version: ${{ env.version }}
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-checker-${{ matrix.artifact }}
          path: dist/site-checker${{ matrix.extension }}

  release:
    needs: build-and-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download Linux x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: site-checker-linux-x64

      - name: Download Linux arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: site-checker-linux-arm64

      - name: Download Windows x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: site-checker-windows-x64

      - name: Download Windows arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: site-checker-windows-arm64

      - name: Download macOS x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: site-checker-macos-x64

      - name: Download macOS arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: site-checker-macos-arm64

      - name: release
        id: release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: site-checker
          prerelease: false
          draft: false
          files: |
            site-checker-linux-x64
            site-checker-linux-arm64
            site-checker-windows-x64
            site-checker-windows-arm64
            site-checker-macos-x64
            site-checker-macos-arm64
          generate_release_notes: true